-- liquibase formatted sql

-- changeset Yura:created-refresh_tokens-table
CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_uuid   VARCHAR                                 NOT NULL,
    jti         VARCHAR(255)                            NOT NULL,
    expire_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

-- changeset Yura:created-jti-uc
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_jti UNIQUE (jti);

-- changeset Yura:created-fc-from-refresh_tokens-to-users
ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER_UUID FOREIGN KEY (user_uuid) REFERENCES users (uuid);

