-- liquibase formatted sql

-- changeset Yura:created-authors-table
CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    birthday   date                                    NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

