-- liquibase formatted sql

-- changeset Yura:created-books-table
CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    genre       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    author_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

-- changeset Yura:created-fc-from-books-table-to-authors-table
ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);

