-- liquibase formatted sql

-- changeset Yura:created-authors-table
CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    birthdate   date                                    NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

